[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
  '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/src/v0.8/'
]
fs_permissions = [
  {access = "read", path = "./broadcast" },
  {access = "read", path = "./reports" },
  {access = "read", path = "./img"}
]
[fuzz]
runs = 1000
[invariant]
runs = 128
depth = 128
fail_on_revert = true


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
